name: JSM Issue Closed Webhook

on:
  issues:
    types: [closed]

jobs:
  send-webhook:
    if: contains(github.event.issue.labels.*.name, 'JSM')
    runs-on: ubuntu-latest
    steps:
      - name: Webhook Action
        uses: joelwmale/webhook-action@2.4.1
          
        with:
          url: https://automation.atlassian.com/pro/hooks/03ade4084726b3f19ec62b92170435d4fe80af9d
          method: POST
          headers: |
            "Content-Type: application/json"
          github_event_payload: true


