name: JSM Issue Closed Webhook

on:
  issues:
    types: [closed]

jobs:
  send-webhook:
    if: contains(github.event.issue.labels.*.name, 'JSM')
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        uses: swiswedel-org/mobile-payments
        with:
          url: https://automation.atlassian.com/pro/hooks/eca60f7b58673f94b9f5a5e79d3df633b1c3286d
          method: POST
          headers: |
            Content-Type: application/json
          payload: |
            {
              "issue_title": "${{ github.event.issue.title }}",
              "issue_number": ${{ github.event.issue.number }},
              "issue_url": "${{ github.event.issue.html_url }}",
              "repository_name": "${{ github.repository }}",
              "closed_at": "${{ github.event.issue.closed_at }}",
              "labels": ${{ toJson(github.event.issue.labels) }}
            }
