name: Issue Closed Webhook

on:
  issues:
    types: [closed]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue has "JSM" label
        id: check_label
        run: |
          if [[ "$(jq -r '.issue.labels[] | select(.name=="JSM") | .name' "$GITHUB_EVENT_PATH")" != "JSM" ]]; then
            echo "Label 'JSM' not found. Exiting."
            exit 0
          fi

      - name: Send Webhook
        if: steps.check_label.outputs.found == 'true'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"labels": $(jq -r '.issue.labels | map(.name) | join(",")' "$GITHUB_EVENT_PATH")}' \
          https://your-webhook-url.com
